platform:ios,'8.0'
pod 'Masonry'
pod 'React', :path => './reactComponent/node_modules/react-native', :subspecs => [
  'Core',
  'RCTImage',
  'RCTNetwork',
  'RCTText',
  'RCTWebSocket',
  # 添加其他你想在工程中使用的依赖。
]
